# Generated by Django 3.2 on 2021-05-18 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_movie_director'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name_plural': 'directors'},
        ),
        migrations.RemoveField(
            model_name='director',
            name='year',
        ),
    ]
