# Generated by Django 3.2 on 2021-05-22 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0003_remove_movie_persons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Category',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='Language',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='MeanRatings',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='NumberComments',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='NumberRates',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ReleaseDate',
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
