# Generated by Django 3.2 on 2021-05-22 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20210522_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Category',
            field=models.CharField(choices=[('AC', 'Action'), ('CO', 'Comedies'), ('RO', 'Romantic'), ('ROM', 'Rom-coms'), ('AD', 'Adventure'), ('MU', 'Musical'), ('DR', 'Drama'), ('HDR', 'Historical drama'), ('SC', 'Sci-fi')], default='CO', max_length=3),
        ),
        migrations.AddField(
            model_name='movie',
            name='Description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='movie',
            name='Language',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='MeanRatings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='movie',
            name='NumberComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='NumberRates',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='ReleaseDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(to='travello.Person'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
