# Generated by Django 3.2 on 2021-05-22 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0005_auto_20210522_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='ReleaseDate',
        ),
    ]
