# Generated by Django 3.2 on 2021-05-24 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_auto_20210518_1720'),
        ('travello', '0006_auto_20210522_0044'),
    ]

    operations = [
    ]
