# Generated by Django 3.2 on 2021-05-24 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_merge_0004_auto_20210518_1720_0006_auto_20210522_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='director',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Director',
        ),
    ]
