# Generated by Django 3.2 on 2021-05-25 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0009_auto_20210525_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='movie',
        ),
    ]
