# Generated by Django 3.2 on 2021-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0010_remove_comment_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(to='travello.Comment'),
        ),
    ]
