# Generated by Django 3.2 on 2021-05-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0011_movie_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Name',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
