# Generated by Django 3.2 on 2021-05-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0012_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='numberDislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='numberLikes',
            field=models.IntegerField(default=0),
        ),
    ]
