# Generated by Django 3.2 on 2021-05-29 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0013_auto_20210529_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
