# Generated by Django 3.2 on 2021-05-29 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0014_movie_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='link',
            field=models.CharField(default='', max_length=150),
        ),
    ]
