# Generated by Django 3.2.4 on 2021-06-13 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0015_alter_movie_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='NumberRates',
        ),
        migrations.RemoveField(
            model_name='person',
            name='Role',
        ),
        migrations.AlterField(
            model_name='comment',
            name='Comment',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.ManyToManyField(blank=True, to='travello.Comment'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='persons',
            field=models.ManyToManyField(blank=True, to='travello.Person'),
        ),
    ]
