# Generated by Django 3.2.4 on 2021-06-13 17:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0016_auto_20210613_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Voters',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), blank=True, default=[], size=None),
        ),
    ]
