# Generated by Django 3.2.4 on 2021-06-13 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0018_alter_movie_voters'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rate',
        ),
    ]
